Repository XLabs/portal-bridge-ui, pull requests merged in 2023-08, with the labels that each got.

#261 #260 - add base support
  package-lock.json
  package.json
  src/components/ShowTx.tsx
  src/components/SmartAddress.tsx
  src/components/TransactionProgress.tsx
  src/components/UnwrapNative.tsx
  src/hooks/useGetSourceParsedTokenAccounts.ts
  src/icons/base.svg
  src/utils/consts.ts
  src/utils/metaMaskChainParameters.ts
Labels: enhancement, do not merge

#301 281 Failed to load token metadata SUI
  package-lock.json
  src/utils/consts.ts
Labels: bug

#323 planned outage - head up banner
  .github/workflows/prettier.yml
  package-lock.json
  package.json
  src/components/HeaderText.tsx
Labels: do not merge

#352 170 Bugfix: Two MATIC options are displayed on “Select a token” pop-up
  src/hooks/useGetSourceParsedTokenAccounts.ts
Labels: bug
